# Generated by Django 2.2.6 on 2019-10-19 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('details', models.CharField(max_length=500)),
                ('nr_rooms', models.IntegerField()),
                ('nr_kitchens', models.IntegerField()),
                ('nr_bathrooms', models.IntegerField()),
                ('surface_mp', models.IntegerField()),
                ('accomodated', models.CharField(choices=[('DT', 'decomandat'), ('NAC', 'nedecomandat'), ('HAC', 'semidecomandat')], default='DT', max_length=10)),
                ('confort', models.CharField(max_length=10)),
                ('floor', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('nr_parking_spots', models.IntegerField()),
                ('nr_balconies', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
